// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_extend1.proto

#ifndef PROTOBUF_player_5fextend1_2eproto__INCLUDED
#define PROTOBUF_player_5fextend1_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
#include "db_option.pb.h"
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_player_5fextend1_2eproto();
void protobuf_AssignDesc_player_5fextend1_2eproto();
void protobuf_ShutdownFile_player_5fextend1_2eproto();

class player_extend1;
class player_extend1_data;
class player_extend1_data_set;
class player_extend1_set;

// ===================================================================

class player_extend1_data : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.player_extend1_data) */ {
 public:
  player_extend1_data();
  virtual ~player_extend1_data();

  player_extend1_data(const player_extend1_data& from);

  inline player_extend1_data& operator=(const player_extend1_data& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const player_extend1_data& default_instance();

  void Swap(player_extend1_data* other);

  // implements Message ----------------------------------------------

  inline player_extend1_data* New() const { return New(NULL); }

  player_extend1_data* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const player_extend1_data& from);
  void MergeFrom(const player_extend1_data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(player_extend1_data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 data1 = 1;
  void clear_data1();
  static const int kData1FieldNumber = 1;
  ::google::protobuf::uint32 data1() const;
  void set_data1(::google::protobuf::uint32 value);

  // optional uint32 data2 = 2;
  void clear_data2();
  static const int kData2FieldNumber = 2;
  ::google::protobuf::uint32 data2() const;
  void set_data2(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.db.player_extend1_data)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 data1_;
  ::google::protobuf::uint32 data2_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_player_5fextend1_2eproto();
  friend void protobuf_AssignDesc_player_5fextend1_2eproto();
  friend void protobuf_ShutdownFile_player_5fextend1_2eproto();

  void InitAsDefaultInstance();
  static player_extend1_data* default_instance_;
};
// -------------------------------------------------------------------

class player_extend1_data_set : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.player_extend1_data_set) */ {
 public:
  player_extend1_data_set();
  virtual ~player_extend1_data_set();

  player_extend1_data_set(const player_extend1_data_set& from);

  inline player_extend1_data_set& operator=(const player_extend1_data_set& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const player_extend1_data_set& default_instance();

  void Swap(player_extend1_data_set* other);

  // implements Message ----------------------------------------------

  inline player_extend1_data_set* New() const { return New(NULL); }

  player_extend1_data_set* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const player_extend1_data_set& from);
  void MergeFrom(const player_extend1_data_set& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(player_extend1_data_set* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.db.player_extend1_data data = 1;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::proto::db::player_extend1_data& data(int index) const;
  ::proto::db::player_extend1_data* mutable_data(int index);
  ::proto::db::player_extend1_data* add_data();
  ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1_data >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1_data >&
      data() const;

  // @@protoc_insertion_point(class_scope:proto.db.player_extend1_data_set)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1_data > data_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_player_5fextend1_2eproto();
  friend void protobuf_AssignDesc_player_5fextend1_2eproto();
  friend void protobuf_ShutdownFile_player_5fextend1_2eproto();

  void InitAsDefaultInstance();
  static player_extend1_data_set* default_instance_;
};
// -------------------------------------------------------------------

class player_extend1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.player_extend1) */ {
 public:
  player_extend1();
  virtual ~player_extend1();

  player_extend1(const player_extend1& from);

  inline player_extend1& operator=(const player_extend1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const player_extend1& default_instance();

  void Swap(player_extend1* other);

  // implements Message ----------------------------------------------

  inline player_extend1* New() const { return New(NULL); }

  player_extend1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const player_extend1& from);
  void MergeFrom(const player_extend1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(player_extend1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional .google.protobuf.Any data_set = 2;
  bool has_data_set() const;
  void clear_data_set();
  static const int kDataSetFieldNumber = 2;
  const ::google::protobuf::Any& data_set() const;
  ::google::protobuf::Any* mutable_data_set();
  ::google::protobuf::Any* release_data_set();
  void set_allocated_data_set(::google::protobuf::Any* data_set);

  // @@protoc_insertion_point(class_scope:proto.db.player_extend1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::Any* data_set_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_player_5fextend1_2eproto();
  friend void protobuf_AssignDesc_player_5fextend1_2eproto();
  friend void protobuf_ShutdownFile_player_5fextend1_2eproto();

  void InitAsDefaultInstance();
  static player_extend1* default_instance_;
};
// -------------------------------------------------------------------

class player_extend1_set : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.player_extend1_set) */ {
 public:
  player_extend1_set();
  virtual ~player_extend1_set();

  player_extend1_set(const player_extend1_set& from);

  inline player_extend1_set& operator=(const player_extend1_set& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const player_extend1_set& default_instance();

  void Swap(player_extend1_set* other);

  // implements Message ----------------------------------------------

  inline player_extend1_set* New() const { return New(NULL); }

  player_extend1_set* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const player_extend1_set& from);
  void MergeFrom(const player_extend1_set& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(player_extend1_set* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.db.player_extend1 data_set = 1;
  int data_set_size() const;
  void clear_data_set();
  static const int kDataSetFieldNumber = 1;
  const ::proto::db::player_extend1& data_set(int index) const;
  ::proto::db::player_extend1* mutable_data_set(int index);
  ::proto::db::player_extend1* add_data_set();
  ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1 >*
      mutable_data_set();
  const ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1 >&
      data_set() const;

  // @@protoc_insertion_point(class_scope:proto.db.player_extend1_set)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1 > data_set_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_player_5fextend1_2eproto();
  friend void protobuf_AssignDesc_player_5fextend1_2eproto();
  friend void protobuf_ShutdownFile_player_5fextend1_2eproto();

  void InitAsDefaultInstance();
  static player_extend1_set* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// player_extend1_data

// optional uint32 data1 = 1;
inline void player_extend1_data::clear_data1() {
  data1_ = 0u;
}
inline ::google::protobuf::uint32 player_extend1_data::data1() const {
  // @@protoc_insertion_point(field_get:proto.db.player_extend1_data.data1)
  return data1_;
}
inline void player_extend1_data::set_data1(::google::protobuf::uint32 value) {
  
  data1_ = value;
  // @@protoc_insertion_point(field_set:proto.db.player_extend1_data.data1)
}

// optional uint32 data2 = 2;
inline void player_extend1_data::clear_data2() {
  data2_ = 0u;
}
inline ::google::protobuf::uint32 player_extend1_data::data2() const {
  // @@protoc_insertion_point(field_get:proto.db.player_extend1_data.data2)
  return data2_;
}
inline void player_extend1_data::set_data2(::google::protobuf::uint32 value) {
  
  data2_ = value;
  // @@protoc_insertion_point(field_set:proto.db.player_extend1_data.data2)
}

// -------------------------------------------------------------------

// player_extend1_data_set

// repeated .proto.db.player_extend1_data data = 1;
inline int player_extend1_data_set::data_size() const {
  return data_.size();
}
inline void player_extend1_data_set::clear_data() {
  data_.Clear();
}
inline const ::proto::db::player_extend1_data& player_extend1_data_set::data(int index) const {
  // @@protoc_insertion_point(field_get:proto.db.player_extend1_data_set.data)
  return data_.Get(index);
}
inline ::proto::db::player_extend1_data* player_extend1_data_set::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:proto.db.player_extend1_data_set.data)
  return data_.Mutable(index);
}
inline ::proto::db::player_extend1_data* player_extend1_data_set::add_data() {
  // @@protoc_insertion_point(field_add:proto.db.player_extend1_data_set.data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1_data >*
player_extend1_data_set::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:proto.db.player_extend1_data_set.data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1_data >&
player_extend1_data_set::data() const {
  // @@protoc_insertion_point(field_list:proto.db.player_extend1_data_set.data)
  return data_;
}

// -------------------------------------------------------------------

// player_extend1

// optional uint32 id = 1;
inline void player_extend1::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 player_extend1::id() const {
  // @@protoc_insertion_point(field_get:proto.db.player_extend1.id)
  return id_;
}
inline void player_extend1::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:proto.db.player_extend1.id)
}

// optional .google.protobuf.Any data_set = 2;
inline bool player_extend1::has_data_set() const {
  return !_is_default_instance_ && data_set_ != NULL;
}
inline void player_extend1::clear_data_set() {
  if (GetArenaNoVirtual() == NULL && data_set_ != NULL) delete data_set_;
  data_set_ = NULL;
}
inline const ::google::protobuf::Any& player_extend1::data_set() const {
  // @@protoc_insertion_point(field_get:proto.db.player_extend1.data_set)
  return data_set_ != NULL ? *data_set_ : *default_instance_->data_set_;
}
inline ::google::protobuf::Any* player_extend1::mutable_data_set() {
  
  if (data_set_ == NULL) {
    data_set_ = new ::google::protobuf::Any;
  }
  // @@protoc_insertion_point(field_mutable:proto.db.player_extend1.data_set)
  return data_set_;
}
inline ::google::protobuf::Any* player_extend1::release_data_set() {
  // @@protoc_insertion_point(field_release:proto.db.player_extend1.data_set)
  
  ::google::protobuf::Any* temp = data_set_;
  data_set_ = NULL;
  return temp;
}
inline void player_extend1::set_allocated_data_set(::google::protobuf::Any* data_set) {
  delete data_set_;
  data_set_ = data_set;
  if (data_set) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto.db.player_extend1.data_set)
}

// -------------------------------------------------------------------

// player_extend1_set

// repeated .proto.db.player_extend1 data_set = 1;
inline int player_extend1_set::data_set_size() const {
  return data_set_.size();
}
inline void player_extend1_set::clear_data_set() {
  data_set_.Clear();
}
inline const ::proto::db::player_extend1& player_extend1_set::data_set(int index) const {
  // @@protoc_insertion_point(field_get:proto.db.player_extend1_set.data_set)
  return data_set_.Get(index);
}
inline ::proto::db::player_extend1* player_extend1_set::mutable_data_set(int index) {
  // @@protoc_insertion_point(field_mutable:proto.db.player_extend1_set.data_set)
  return data_set_.Mutable(index);
}
inline ::proto::db::player_extend1* player_extend1_set::add_data_set() {
  // @@protoc_insertion_point(field_add:proto.db.player_extend1_set.data_set)
  return data_set_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1 >*
player_extend1_set::mutable_data_set() {
  // @@protoc_insertion_point(field_mutable_list:proto.db.player_extend1_set.data_set)
  return &data_set_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::db::player_extend1 >&
player_extend1_set::data_set() const {
  // @@protoc_insertion_point(field_list:proto.db.player_extend1_set.data_set)
  return data_set_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_player_5fextend1_2eproto__INCLUDED
