// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: call_command.proto

#ifndef PROTOBUF_call_5fcommand_2eproto__INCLUDED
#define PROTOBUF_call_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_call_5fcommand_2eproto();
void protobuf_AssignDesc_call_5fcommand_2eproto();
void protobuf_ShutdownFile_call_5fcommand_2eproto();

class call_command;

// ===================================================================

class call_command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.call_command) */ {
 public:
  call_command();
  virtual ~call_command();

  call_command(const call_command& from);

  inline call_command& operator=(const call_command& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const call_command& default_instance();

  void Swap(call_command* other);

  // implements Message ----------------------------------------------

  inline call_command* New() const { return New(NULL); }

  call_command* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const call_command& from);
  void MergeFrom(const call_command& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(call_command* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string sql = 1;
  bool has_sql() const;
  void clear_sql();
  static const int kSqlFieldNumber = 1;
  const ::std::string& sql() const;
  void set_sql(const ::std::string& value);
  void set_sql(const char* value);
  void set_sql(const char* value, size_t size);
  ::std::string* mutable_sql();
  ::std::string* release_sql();
  void set_allocated_sql(::std::string* sql);

  // repeated bytes args = 2;
  int args_size() const;
  void clear_args();
  static const int kArgsFieldNumber = 2;
  const ::std::string& args(int index) const;
  ::std::string* mutable_args(int index);
  void set_args(int index, const ::std::string& value);
  void set_args(int index, const char* value);
  void set_args(int index, const void* value, size_t size);
  ::std::string* add_args();
  void add_args(const ::std::string& value);
  void add_args(const char* value);
  void add_args(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& args() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_args();

  // @@protoc_insertion_point(class_scope:proto.db.call_command)
 private:
  inline void set_has_sql();
  inline void clear_has_sql();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr sql_;
  ::google::protobuf::RepeatedPtrField< ::std::string> args_;
  friend void  protobuf_AddDesc_call_5fcommand_2eproto();
  friend void protobuf_AssignDesc_call_5fcommand_2eproto();
  friend void protobuf_ShutdownFile_call_5fcommand_2eproto();

  void InitAsDefaultInstance();
  static call_command* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// call_command

// required string sql = 1;
inline bool call_command::has_sql() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void call_command::set_has_sql() {
  _has_bits_[0] |= 0x00000001u;
}
inline void call_command::clear_has_sql() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void call_command::clear_sql() {
  sql_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sql();
}
inline const ::std::string& call_command::sql() const {
  // @@protoc_insertion_point(field_get:proto.db.call_command.sql)
  return sql_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void call_command::set_sql(const ::std::string& value) {
  set_has_sql();
  sql_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.db.call_command.sql)
}
inline void call_command::set_sql(const char* value) {
  set_has_sql();
  sql_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.db.call_command.sql)
}
inline void call_command::set_sql(const char* value, size_t size) {
  set_has_sql();
  sql_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.db.call_command.sql)
}
inline ::std::string* call_command::mutable_sql() {
  set_has_sql();
  // @@protoc_insertion_point(field_mutable:proto.db.call_command.sql)
  return sql_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* call_command::release_sql() {
  // @@protoc_insertion_point(field_release:proto.db.call_command.sql)
  clear_has_sql();
  return sql_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void call_command::set_allocated_sql(::std::string* sql) {
  if (sql != NULL) {
    set_has_sql();
  } else {
    clear_has_sql();
  }
  sql_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sql);
  // @@protoc_insertion_point(field_set_allocated:proto.db.call_command.sql)
}

// repeated bytes args = 2;
inline int call_command::args_size() const {
  return args_.size();
}
inline void call_command::clear_args() {
  args_.Clear();
}
inline const ::std::string& call_command::args(int index) const {
  // @@protoc_insertion_point(field_get:proto.db.call_command.args)
  return args_.Get(index);
}
inline ::std::string* call_command::mutable_args(int index) {
  // @@protoc_insertion_point(field_mutable:proto.db.call_command.args)
  return args_.Mutable(index);
}
inline void call_command::set_args(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:proto.db.call_command.args)
  args_.Mutable(index)->assign(value);
}
inline void call_command::set_args(int index, const char* value) {
  args_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.db.call_command.args)
}
inline void call_command::set_args(int index, const void* value, size_t size) {
  args_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.db.call_command.args)
}
inline ::std::string* call_command::add_args() {
  // @@protoc_insertion_point(field_add_mutable:proto.db.call_command.args)
  return args_.Add();
}
inline void call_command::add_args(const ::std::string& value) {
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:proto.db.call_command.args)
}
inline void call_command::add_args(const char* value) {
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:proto.db.call_command.args)
}
inline void call_command::add_args(const void* value, size_t size) {
  args_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:proto.db.call_command.args)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
call_command::args() const {
  // @@protoc_insertion_point(field_list:proto.db.call_command.args)
  return args_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
call_command::mutable_args() {
  // @@protoc_insertion_point(field_mutable_list:proto.db.call_command.args)
  return &args_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_call_5fcommand_2eproto__INCLUDED
