// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_option.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "db_option.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {


}  // namespace


void protobuf_AssignDesc_db_5foption_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_db_5foption_2eproto() {
  protobuf_AddDesc_db_5foption_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "db_option.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_db_5foption_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_db_5foption_2eproto() {
}

void protobuf_AddDesc_db_5foption_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_db_5foption_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017db_option.proto\032 google/protobuf/descr"
    "iptor.proto:6\n\013primary_key\022\037.google.prot"
    "obuf.MessageOptions\030\320\206\003 \001(\t:7\n\016serialize"
    "_type\022\035.google.protobuf.FieldOptions\030\321\206\003"
    " \001(\r", 164);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "db_option.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50001, 13, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_db_5foption_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_db_5foption_2eproto {
  StaticDescriptorInitializer_db_5foption_2eproto() {
    protobuf_AddDesc_db_5foption_2eproto();
  }
} static_descriptor_initializer_db_5foption_2eproto_;
const ::std::string primary_key_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  primary_key(kPrimaryKeyFieldNumber, primary_key_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  serialize_type(kSerializeTypeFieldNumber, 0u);

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
