// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delete_command.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "delete_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {

namespace {

const ::google::protobuf::Descriptor* delete_command_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  delete_command_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_delete_5fcommand_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_delete_5fcommand_2eproto() {
  protobuf_AddDesc_delete_5fcommand_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "delete_command.proto");
  GOOGLE_CHECK(file != NULL);
  delete_command_descriptor_ = file->message_type(0);
  static const int delete_command_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(delete_command, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(delete_command, table_name_),
  };
  delete_command_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      delete_command_descriptor_,
      delete_command::internal_default_instance(),
      delete_command_offsets_,
      -1,
      -1,
      -1,
      sizeof(delete_command),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(delete_command, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_delete_5fcommand_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      delete_command_descriptor_, delete_command::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_delete_5fcommand_2eproto() {
  delete_command_default_instance_.Shutdown();
  delete delete_command_reflection_;
}

void protobuf_InitDefaults_delete_5fcommand_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  delete_command_default_instance_.DefaultConstruct();
  delete_command_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_delete_5fcommand_2eproto_once_);
void protobuf_InitDefaults_delete_5fcommand_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_delete_5fcommand_2eproto_once_,
                 &protobuf_InitDefaults_delete_5fcommand_2eproto_impl);
}
void protobuf_AddDesc_delete_5fcommand_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_delete_5fcommand_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024delete_command.proto\022\010proto.db\"0\n\016dele"
    "te_command\022\n\n\002id\030\001 \001(\004\022\022\n\ntable_name\030\002 \001"
    "(\tb\006proto3", 90);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "delete_command.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_delete_5fcommand_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_delete_5fcommand_2eproto_once_);
void protobuf_AddDesc_delete_5fcommand_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_delete_5fcommand_2eproto_once_,
                 &protobuf_AddDesc_delete_5fcommand_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_delete_5fcommand_2eproto {
  StaticDescriptorInitializer_delete_5fcommand_2eproto() {
    protobuf_AddDesc_delete_5fcommand_2eproto();
  }
} static_descriptor_initializer_delete_5fcommand_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int delete_command::kIdFieldNumber;
const int delete_command::kTableNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

delete_command::delete_command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_delete_5fcommand_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.db.delete_command)
}

void delete_command::InitAsDefaultInstance() {
}

delete_command::delete_command(const delete_command& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:proto.db.delete_command)
}

void delete_command::SharedCtor() {
  dirty_ = false;
  table_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

delete_command::~delete_command() {
  // @@protoc_insertion_point(destructor:proto.db.delete_command)
  SharedDtor();
}

void delete_command::SharedDtor() {
  table_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void delete_command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* delete_command::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return delete_command_descriptor_;
}

const delete_command& delete_command::default_instance() {
  protobuf_InitDefaults_delete_5fcommand_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<delete_command> delete_command_default_instance_;

delete_command* delete_command::New(::google::protobuf::Arena* arena) const {
  delete_command* n = new delete_command;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void delete_command::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.db.delete_command)
  id_ = GOOGLE_ULONGLONG(0);
  table_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool delete_command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.db.delete_command)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 id = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_table_name;
        break;
      }

      // optional string table_name = 2;
      case 2: {
        if (tag == 18) {
         parse_table_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->table_name().data(), this->table_name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.db.delete_command.table_name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.db.delete_command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.db.delete_command)
  return false;
#undef DO_
}

void delete_command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.db.delete_command)
  // optional uint64 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->id(), output);
  }

  // optional string table_name = 2;
  if (this->table_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table_name().data(), this->table_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.db.delete_command.table_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->table_name(), output);
  }

  // @@protoc_insertion_point(serialize_end:proto.db.delete_command)
}

::google::protobuf::uint8* delete_command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.db.delete_command)
  // optional uint64 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->id(), target);
  }

  // optional string table_name = 2;
  if (this->table_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table_name().data(), this->table_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.db.delete_command.table_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->table_name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:proto.db.delete_command)
  return target;
}

size_t delete_command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.db.delete_command)
  size_t total_size = 0;

  // optional uint64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->id());
  }

  // optional string table_name = 2;
  if (this->table_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void delete_command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.db.delete_command)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const delete_command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const delete_command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.db.delete_command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.db.delete_command)
    UnsafeMergeFrom(*source);
  }
}

void delete_command::MergeFrom(const delete_command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.db.delete_command)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void delete_command::UnsafeMergeFrom(const delete_command& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.table_name().size() > 0) {

    table_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_name_);
  }
}

void delete_command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.db.delete_command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void delete_command::CopyFrom(const delete_command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.db.delete_command)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool delete_command::IsInitialized() const {

  return true;
}

void delete_command::Swap(delete_command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void delete_command::InternalSwap(delete_command* other) {
  std::swap(id_, other->id_);
  table_name_.Swap(&other->table_name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata delete_command::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = delete_command_descriptor_;
  metadata.reflection = delete_command_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// delete_command

// optional uint64 id = 1;
void delete_command::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
dirty_ = true;
}
::google::protobuf::uint64 delete_command::id() const {
  // @@protoc_insertion_point(field_get:proto.db.delete_command.id)
  return id_;
}
void delete_command::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  dirty_ = true;
  // @@protoc_insertion_point(field_set:proto.db.delete_command.id)
}

// optional string table_name = 2;
void delete_command::clear_table_name() {
  table_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
dirty_ = true;
}
const ::std::string& delete_command::table_name() const {
  // @@protoc_insertion_point(field_get:proto.db.delete_command.table_name)
  return table_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void delete_command::set_table_name(const ::std::string& value) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  dirty_ = true;
  // @@protoc_insertion_point(field_set:proto.db.delete_command.table_name)
}
void delete_command::set_table_name(const char* value) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_char:proto.db.delete_command.table_name)
}
void delete_command::set_table_name(const char* value, size_t size) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_pointer:proto.db.delete_command.table_name)
}
::std::string* delete_command::mutable_table_name() {
  
  // @@protoc_insertion_point(field_mutable:proto.db.delete_command.table_name)
  return table_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* delete_command::release_table_name() {
  // @@protoc_insertion_point(field_release:proto.db.delete_command.table_name)
  
  dirty_ = true;
  return table_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void delete_command::set_allocated_table_name(::std::string* table_name) {
  if (table_name != NULL) {
    
  } else {
    
  }
  table_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), table_name);
  dirty_ = true;
  // @@protoc_insertion_point(field_set_allocated:proto.db.delete_command.table_name)
}

inline const delete_command* delete_command::internal_default_instance() {
  return &delete_command_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)
