// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nop_command.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "nop_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {

namespace {

const ::google::protobuf::Descriptor* nop_command_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  nop_command_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_nop_5fcommand_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_nop_5fcommand_2eproto() {
  protobuf_AddDesc_nop_5fcommand_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "nop_command.proto");
  GOOGLE_CHECK(file != NULL);
  nop_command_descriptor_ = file->message_type(0);
  static const int nop_command_offsets_[1] = {
  };
  nop_command_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      nop_command_descriptor_,
      nop_command::default_instance_,
      nop_command_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(nop_command, _has_bits_[0]),
      -1,
      -1,
      sizeof(nop_command),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(nop_command, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_nop_5fcommand_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      nop_command_descriptor_, &nop_command::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_nop_5fcommand_2eproto() {
  delete nop_command::default_instance_;
  delete nop_command_reflection_;
}

void protobuf_AddDesc_nop_5fcommand_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_nop_5fcommand_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021nop_command.proto\022\010proto.db\"\r\n\013nop_com"
    "mand", 44);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "nop_command.proto", &protobuf_RegisterTypes);
  nop_command::default_instance_ = new nop_command();
  nop_command::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_nop_5fcommand_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_nop_5fcommand_2eproto {
  StaticDescriptorInitializer_nop_5fcommand_2eproto() {
    protobuf_AddDesc_nop_5fcommand_2eproto();
  }
} static_descriptor_initializer_nop_5fcommand_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

nop_command::nop_command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.db.nop_command)
}

void nop_command::InitAsDefaultInstance() {
}

nop_command::nop_command(const nop_command& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:proto.db.nop_command)
}

void nop_command::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

nop_command::~nop_command() {
  // @@protoc_insertion_point(destructor:proto.db.nop_command)
  SharedDtor();
}

void nop_command::SharedDtor() {
  if (this != default_instance_) {
  }
}

void nop_command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* nop_command::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return nop_command_descriptor_;
}

const nop_command& nop_command::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_nop_5fcommand_2eproto();
  return *default_instance_;
}

nop_command* nop_command::default_instance_ = NULL;

nop_command* nop_command::New(::google::protobuf::Arena* arena) const {
  nop_command* n = new nop_command;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void nop_command::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.db.nop_command)
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool nop_command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.db.nop_command)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:proto.db.nop_command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.db.nop_command)
  return false;
#undef DO_
}

void nop_command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.db.nop_command)
  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.db.nop_command)
}

::google::protobuf::uint8* nop_command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.db.nop_command)
  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.db.nop_command)
  return target;
}

int nop_command::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:proto.db.nop_command)
  int total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void nop_command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.db.nop_command)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const nop_command* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const nop_command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.db.nop_command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.db.nop_command)
    MergeFrom(*source);
  }
}

void nop_command::MergeFrom(const nop_command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.db.nop_command)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void nop_command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.db.nop_command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void nop_command::CopyFrom(const nop_command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.db.nop_command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool nop_command::IsInitialized() const {

  return true;
}

void nop_command::Swap(nop_command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void nop_command::InternalSwap(nop_command* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata nop_command::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = nop_command_descriptor_;
  metadata.reflection = nop_command_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// nop_command

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)
