// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_command.proto

#ifndef PROTOBUF_query_5fcommand_2eproto__INCLUDED
#define PROTOBUF_query_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_query_5fcommand_2eproto();
void protobuf_InitDefaults_query_5fcommand_2eproto();
void protobuf_AssignDesc_query_5fcommand_2eproto();
void protobuf_ShutdownFile_query_5fcommand_2eproto();

class query_command;

// ===================================================================

class query_command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.query_command) */ {
 public:
  query_command();
  virtual ~query_command();

  query_command(const query_command& from);

  inline query_command& operator=(const query_command& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const query_command& default_instance();

  static const query_command* internal_default_instance();

  void Swap(query_command* other);

  // implements Message ----------------------------------------------

  inline query_command* New() const { return New(NULL); }

  query_command* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const query_command& from);
  void MergeFrom(const query_command& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(query_command* other);
  void UnsafeMergeFrom(const query_command& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  bool is_dirty() const { return dirty_; }
  void clear_dirty() { dirty_ = false; }
  // optional string table_name = 1;
  void clear_table_name();
  static const int kTableNameFieldNumber = 1;
  const ::std::string& table_name() const;
  void set_table_name(const ::std::string& value);
  void set_table_name(const char* value);
  void set_table_name(const char* value, size_t size);
  ::std::string* mutable_table_name();
  ::std::string* release_table_name();
  void set_allocated_table_name(::std::string* table_name);

  // optional string where_clause = 2;
  void clear_where_clause();
  static const int kWhereClauseFieldNumber = 2;
  const ::std::string& where_clause() const;
  void set_where_clause(const ::std::string& value);
  void set_where_clause(const char* value);
  void set_where_clause(const char* value, size_t size);
  ::std::string* mutable_where_clause();
  ::std::string* release_where_clause();
  void set_allocated_where_clause(::std::string* where_clause);

  // repeated string args = 3;
  int args_size() const;
  void clear_args();
  static const int kArgsFieldNumber = 3;
  const ::std::string& args(int index) const;
  ::std::string* mutable_args(int index);
  void set_args(int index, const ::std::string& value);
  void set_args(int index, const char* value);
  void set_args(int index, const char* value, size_t size);
  ::std::string* add_args();
  void add_args(const ::std::string& value);
  void add_args(const char* value);
  void add_args(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& args() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_args();

  // @@protoc_insertion_point(class_scope:proto.db.query_command)
 private:
  bool dirty_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> args_;
  ::google::protobuf::internal::ArenaStringPtr table_name_;
  ::google::protobuf::internal::ArenaStringPtr where_clause_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_query_5fcommand_2eproto_impl();
  friend void  protobuf_AddDesc_query_5fcommand_2eproto_impl();
  friend void protobuf_AssignDesc_query_5fcommand_2eproto();
  friend void protobuf_ShutdownFile_query_5fcommand_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<query_command> query_command_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// query_command

// optional string table_name = 1;
inline void query_command::clear_table_name() {
  table_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
dirty_ = true;
}
inline const ::std::string& query_command::table_name() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.table_name)
  return table_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_command::set_table_name(const ::std::string& value) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  dirty_ = true;
  // @@protoc_insertion_point(field_set:proto.db.query_command.table_name)
}
inline void query_command::set_table_name(const char* value) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.table_name)
}
inline void query_command::set_table_name(const char* value, size_t size) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.table_name)
}
inline ::std::string* query_command::mutable_table_name() {
  
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.table_name)
  return table_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* query_command::release_table_name() {
  // @@protoc_insertion_point(field_release:proto.db.query_command.table_name)
  
  dirty_ = true;
  return table_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_command::set_allocated_table_name(::std::string* table_name) {
  if (table_name != NULL) {
    
  } else {
    
  }
  table_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), table_name);
  dirty_ = true;
  // @@protoc_insertion_point(field_set_allocated:proto.db.query_command.table_name)
}

// optional string where_clause = 2;
inline void query_command::clear_where_clause() {
  where_clause_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
dirty_ = true;
}
inline const ::std::string& query_command::where_clause() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.where_clause)
  return where_clause_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_command::set_where_clause(const ::std::string& value) {
  
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  dirty_ = true;
  // @@protoc_insertion_point(field_set:proto.db.query_command.where_clause)
}
inline void query_command::set_where_clause(const char* value) {
  
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.where_clause)
}
inline void query_command::set_where_clause(const char* value, size_t size) {
  
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.where_clause)
}
inline ::std::string* query_command::mutable_where_clause() {
  
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.where_clause)
  return where_clause_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* query_command::release_where_clause() {
  // @@protoc_insertion_point(field_release:proto.db.query_command.where_clause)
  
  dirty_ = true;
  return where_clause_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_command::set_allocated_where_clause(::std::string* where_clause) {
  if (where_clause != NULL) {
    
  } else {
    
  }
  where_clause_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), where_clause);
  dirty_ = true;
  // @@protoc_insertion_point(field_set_allocated:proto.db.query_command.where_clause)
}

// repeated string args = 3;
inline int query_command::args_size() const {
  return args_.size();
}
inline void query_command::clear_args() {
  args_.Clear();
dirty_ = true;
}
inline const ::std::string& query_command::args(int index) const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.args)
  return args_.Get(index);
}
inline ::std::string* query_command::mutable_args(int index) {
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.args)
  return args_.Mutable(index);
}
inline void query_command::set_args(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:proto.db.query_command.args)
  dirty_ = true;
  args_.Mutable(index)->assign(value);
}
inline void query_command::set_args(int index, const char* value) {
  args_.Mutable(index)->assign(value);
  dirty_ = true;
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.args)
}
inline void query_command::set_args(int index, const char* value, size_t size) {
  args_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  dirty_ = true;
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.args)
}
inline ::std::string* query_command::add_args() {
  // @@protoc_insertion_point(field_add_mutable:proto.db.query_command.args)
  dirty_ = true;
  return args_.Add();
}
inline void query_command::add_args(const ::std::string& value) {
  args_.Add()->assign(value);
  dirty_ = true;
  // @@protoc_insertion_point(field_add:proto.db.query_command.args)
}
inline void query_command::add_args(const char* value) {
  args_.Add()->assign(value);
  dirty_ = true;
  // @@protoc_insertion_point(field_add_char:proto.db.query_command.args)
}
inline void query_command::add_args(const char* value, size_t size) {
  args_.Add()->assign(reinterpret_cast<const char*>(value), size);
  dirty_ = true;
  // @@protoc_insertion_point(field_add_pointer:proto.db.query_command.args)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
query_command::args() const {
  // @@protoc_insertion_point(field_list:proto.db.query_command.args)
  return args_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
query_command::mutable_args() {
  // @@protoc_insertion_point(field_mutable_list:proto.db.query_command.args)
  return &args_;
}

inline const query_command* query_command::internal_default_instance() {
  return &query_command_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_query_5fcommand_2eproto__INCLUDED
