// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: select_command.proto

#ifndef PROTOBUF_select_5fcommand_2eproto__INCLUDED
#define PROTOBUF_select_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_select_5fcommand_2eproto();
void protobuf_InitDefaults_select_5fcommand_2eproto();
void protobuf_AssignDesc_select_5fcommand_2eproto();
void protobuf_ShutdownFile_select_5fcommand_2eproto();

class select_command;

// ===================================================================

class select_command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.select_command) */ {
 public:
  select_command();
  virtual ~select_command();

  select_command(const select_command& from);

  inline select_command& operator=(const select_command& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const select_command& default_instance();

  static const select_command* internal_default_instance();

  void Swap(select_command* other);

  // implements Message ----------------------------------------------

  inline select_command* New() const { return New(NULL); }

  select_command* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const select_command& from);
  void MergeFrom(const select_command& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(select_command* other);
  void UnsafeMergeFrom(const select_command& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  bool is_dirty() const { return dirty_; }
  void clear_dirty() { dirty_ = false; }
  // optional uint64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // optional string table_name = 2;
  void clear_table_name();
  static const int kTableNameFieldNumber = 2;
  const ::std::string& table_name() const;
  void set_table_name(const ::std::string& value);
  void set_table_name(const char* value);
  void set_table_name(const char* value, size_t size);
  ::std::string* mutable_table_name();
  ::std::string* release_table_name();
  void set_allocated_table_name(::std::string* table_name);

  // @@protoc_insertion_point(class_scope:proto.db.select_command)
 private:
  bool dirty_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr table_name_;
  ::google::protobuf::uint64 id_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_select_5fcommand_2eproto_impl();
  friend void  protobuf_AddDesc_select_5fcommand_2eproto_impl();
  friend void protobuf_AssignDesc_select_5fcommand_2eproto();
  friend void protobuf_ShutdownFile_select_5fcommand_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<select_command> select_command_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// select_command

// optional uint64 id = 1;
inline void select_command::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
dirty_ = true;
}
inline ::google::protobuf::uint64 select_command::id() const {
  // @@protoc_insertion_point(field_get:proto.db.select_command.id)
  return id_;
}
inline void select_command::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  dirty_ = true;
  // @@protoc_insertion_point(field_set:proto.db.select_command.id)
}

// optional string table_name = 2;
inline void select_command::clear_table_name() {
  table_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
dirty_ = true;
}
inline const ::std::string& select_command::table_name() const {
  // @@protoc_insertion_point(field_get:proto.db.select_command.table_name)
  return table_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void select_command::set_table_name(const ::std::string& value) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  dirty_ = true;
  // @@protoc_insertion_point(field_set:proto.db.select_command.table_name)
}
inline void select_command::set_table_name(const char* value) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_char:proto.db.select_command.table_name)
}
inline void select_command::set_table_name(const char* value, size_t size) {
  
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  dirty_ = true;
  // @@protoc_insertion_point(field_set_pointer:proto.db.select_command.table_name)
}
inline ::std::string* select_command::mutable_table_name() {
  
  // @@protoc_insertion_point(field_mutable:proto.db.select_command.table_name)
  return table_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* select_command::release_table_name() {
  // @@protoc_insertion_point(field_release:proto.db.select_command.table_name)
  
  dirty_ = true;
  return table_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void select_command::set_allocated_table_name(::std::string* table_name) {
  if (table_name != NULL) {
    
  } else {
    
  }
  table_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), table_name);
  dirty_ = true;
  // @@protoc_insertion_point(field_set_allocated:proto.db.select_command.table_name)
}

inline const select_command* select_command::internal_default_instance() {
  return &select_command_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_select_5fcommand_2eproto__INCLUDED
